name: base
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anaconda-anon-usage=0.4.4=py311hfc0e8ea_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - blas=1.0=mkl
  - blosc=1.21.5=hc2324a3_1
  - boltons=23.0.0=py311h06a4308_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.16.0=py311h5eee18b_1
  - chardet=4.0.0=py311h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - cmake=3.26.4=h96355d8_0
  - conda=24.11.2=py311h38be061_0
  - conda-build=24.5.1=py311h06a4308_0
  - conda-content-trust=0.2.0=py311h06a4308_1
  - conda-index=0.5.0=py311h06a4308_0
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py311h06a4308_0
  - conda-package-streaming=0.10.0=py311h06a4308_0
  - contourpy=1.3.1=py311hd18a35c_0
  - cryptography=42.0.5=py311hdda0065_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.5=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h9033bb2_6
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distro=1.9.0=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - fmt=9.1.0=hdb19cb5_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py311h2dc5d0c_1
  - freetype=2.12.1=h4a9f257_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozendict=2.4.2=py311h06a4308_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glm=0.9.9.8=h00ab1b0_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.1.1=py311hfdbb021_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.14.3=nompi_h4f84152_101
  - icu=73.2=h59595ed_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.25.0=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jinja2=3.1.4=py311h06a4308_0
  - jpeg=9e=h5eee18b_2
  - jsonpatch=1.33=py311h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py311h92ebd52_6
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libclang=14.0.6=default_h7634d5b_1
  - libclang13=14.0.6=default_h9986a30_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.10.1.7=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.6.82=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=8.4.0=hdf63c60_16
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hac7e632_1003
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblief=0.12.3=h6a678d5_0
  - libllvm14=14.0.6=hcd5def8_4
  - libmamba=1.5.11=hfe524e5_0
  - libmambapy=1.5.11=py311haf1ee3a_0
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.2=h9ac9557_1
  - libpng=1.6.43=h2797004_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsolv=0.7.24=he621ea3_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.5=hfdd30dd_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=hd590300_1001
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-base=3.10.0=py311h2b939e6_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - menuinst=2.1.1=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - molvs=0.1.1=py_0
  - more-itertools=10.1.0=py311h06a4308_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openbabel=3.1.1=py311h8b422cb_9
  - openblas-devel=0.3.2=0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openldap=2.6.5=h389dcaa_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.1=py311h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.17.2=h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pkginfo=1.10.0=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.0.1=py311h38be061_1008
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-lief=0.12.3=py311h6a678d5_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycairo=1.27.0=py311h124c5f0_0
  - pycosat=0.6.6=py311h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - pymol-open-source=3.0.0=py311hbd307dc_8
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.8=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.11=5_cp311
  - pytorch=2.4.0=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.2=hb6262e9_11
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - reportlab=4.2.5=py311h9ecbd09_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py311h06a4308_0
  - rhash=1.4.3=hdbd6064_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - setuptools=69.5.1=py311h06a4308_0
  - sip=6.7.12=py311hb755f60_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h8bd8927_1
  - soupsieve=2.5=py311h06a4308_0
  - sqlalchemy=2.0.36=py311h9ecbd09_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.4.0=py311_cu118
  - torchtriton=3.0.0=py311
  - torchvision=0.19.0=py311_cu118
  - tqdm=4.66.4=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - truststore=0.8.0=py311h06a4308_0
  - typing-extensions=4.11.0=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h9ecbd09_1
  - urllib3=2.2.2=py311h06a4308_0
  - vina=1.2.5=py311hfdbb021_5
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py311h06a4308_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - autodocktools-py3==1.5.7.post1+12.ga62a5d9
      - babel==2.17.0
      - bleach==6.2.0
      - comm==0.2.2
      - debugpy==1.8.14
      - defusedxml==0.7.1
      - dnspython==2.6.1
      - easydict==1.13
      - espsim==0.0.1
      - expecttest==0.2.1
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gemmi==0.7.0
      - grpcio==1.68.1
      - h11==0.14.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - hypothesis==6.108.4
      - ipykernel==6.29.5
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - joblib==1.4.2
      - json5==0.12.0
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - lintrunner==0.12.5
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - lxml==5.3.0
      - markdown==3.7
      - meeko==0.6.1
      - minkowskiengine==0.5.4
      - mistune==3.1.3
      - multidict==6.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.0
      - notebook-shim==0.2.4
      - numba==0.60.0
      - optree==0.12.1
      - overrides==7.7.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - plip==2.4.0
      - prometheus-client==0.21.1
      - propcache==0.2.1
      - protobuf==5.29.2
      - puresnet==0.1
      - python-etcd==0.4.5
      - python-json-logger==3.3.0
      - pyzmq==26.4.0
      - rdkit==2024.3.6
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - torch-cluster==1.6.3+pt24cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu118
      - torch-sparse==0.6.18+pt24cu118
      - torch-spline-conv==1.2.2+pt24cu118
      - torchelastic==0.2.2
      - tornado==6.4.2
      - types-dataclasses==0.6.6
      - types-python-dateutil==2.9.0.20241206
      - unimol-tools==0.1.2.post2
      - uri-template==1.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - yarl==1.18.3
prefix: /opt/conda
